/**
 * UI Translations dictionary for RERA Hub.
 * Supports English (en), Hindi (hi), Marathi (mr), and Kannada (kn).
 */

export const UI_TRANSLATIONS = {
  en: {
    hero_eyebrow: "Section 18 statutory interest compliant",
    hero_title: "compensation calculator",
    hero_lead: "Instantly estimate your RERA compensation — statutory interest, refund amounts, and milestone payment delays under Section 18.",
    btn_start: "Start calculator",
    btn_change_state: "Change state",
    btn_faq: "Browse legal FAQ",
    
    // Calculator Form
    form_title: "Calculate your RERA compensation",
    form_lead: "Estimate interest receivable for delayed possession under Section 18, calibrated to state-specific SBI MCLR guidelines.",
    input_mode: "Input mode",
    mode_amount: "Amount",
    mode_installments: "Installments schedule",
    state_rules: "State authority / rules",
    amount_paid: "Amount paid (₹)",
    promised_date: "Promised date",
    actual_date: "Actual / end date",
    rera_spread: "RERA spread (%) from state config",
    latest_mclr: "Latest SBI highest MCLR (%)",
    override_mclr: "Override with a fixed MCLR (disable period-wise dynamic rates)",
    fixed_rate: "Fixed effective rate:",
    dynamic_rate: "Dynamic MCLR + dated",
    spread_label: "spread",
    btn_calculate: "Calculate now",
    btn_calculating: "Calculating…",
    
    // Report
    report_title: "RERA interest calculation report",
    report_subtitle: "Generated by RERA Hub penalty calculator",
    btn_share: "Share",
    btn_print: "Print report",
    stat_principal: "Principal amount",
    stat_interest: "Interest accrued",
    stat_total: "Total payout",
    stat_delay: "Delay period",
    stat_days: "days",
    
    // Financial Analytics
    analytics_title: "Financial analytics",
    principal_share: "Principal share",
    interest_share: "Interest share",
    daily_rate: "Daily rate",
    monthly_accrual: "Monthly accrual",
    avg_daily_interest: "Avg daily interest",
    disclaimer: "This report is for informational purposes only. Consult a legal professional for official RERA filings.",
    methodology_title: "Methodology note:",
    methodology_dynamic: "By default this calculator applies SBI highest MCLR and the dated state spread config for each segment of the delay. Weighted-average rate is shown for reference.",
    methodology_fixed: "A fixed MCLR override was used across the full delay period.",
    methodology_spreads: "State spreads come from curated files in",
    methodology_mclr: "MCLR sourced from",
    
    // Form M Workspace
    workspace_eyebrow: "Interactive Legal Assistant",
    workspace_title: "Prepare RERA Complaint",
    workspace_lead: "Pre-fill your official state complaint petition below, edit details, and export directly.",
    section_edit_details: "1. Edit Petition Details",
    label_cname: "Complainant Name",
    label_caddress: "Complainant Address",
    label_ccontact: "Complainant Contact (Email / Phone)",
    label_pname: "Project Name",
    label_promoter: "Promoter / Developer Name",
    label_promoter_addr: "Promoter Address",
    label_reg_no: "RERA Registration No.",
    label_booking_date: "Booking Date",
    label_agreement_date: "Agreement for Sale Date",
    
    section_workspace: "2. Complaint Draft Workspace",
    placeholder_editor: "Draft content will appear here...",
    btn_download_word: "Download Word (.doc)",
    btn_download_pdf: "Download PDF (.pdf)",
    btn_copy: "Copy to Clipboard",
    btn_copied: "Copied",
    
    // FAQ Section
    faq_eyebrow: "RERA legal FAQ",
    faq_title: "Expert answers to central & state RERA questions",
    faq_subtitle: "topics · informative only, not legal advice",
    
    // How-to Section
    howto_title: "How to calculate your RERA delayed-possession interest",
    howto_step1: "Choose your state — each authority sets its own interest formula (simple vs monthly compound, and the MCLR spread).",
    howto_step2: "Enter key dates — promised possession and actual/end date define the delay window.",
    howto_step3: "Enter the amount paid — the principal on which Section 18 delay interest is estimated for the possession delay window.",
    howto_step4: "Review the report — principal, interest, delay days, and a printable breakdown for your complaint file.",
    
    footer_desc: "An interactive statutory interest estimator for homebuyers under the Real Estate (Regulation and Development) Act, 2016.",
    footer_disclaimer: "Disclaimer: Estimates only, based on Section 18/19-style SBI MCLR + spread rules. Actual awards are decided by the State RERA Authority / Adjudicating Officer after reviewing case facts. Not legal advice."
  },
  hi: {
    hero_eyebrow: "धारा 18 वैधानिक ब्याज के अनुरूप",
    hero_title: "मुआवजा कैलकुलेटर",
    hero_lead: "तुरंत अपने रेरा मुआवजे का अनुमान लगाएं — धारा 18 के तहत वैधानिक ब्याज, वापसी राशि और मील का पत्थर भुगतान में देरी।",
    btn_start: "कैलकुलेटर शुरू करें",
    btn_change_state: "राज्य बदलें",
    btn_faq: "कानूनी प्रश्नोत्तर पढ़ें",
    
    // Calculator Form
    form_title: "अपने रेरा मुआवजे की गणना करें",
    form_lead: "धारा 18 के तहत विलंबित कब्जे के लिए प्राप्य ब्याज का अनुमान लगाएं, जो राज्य-विशिष्ट एसबीआई एमसीएलआर दिशानिर्देशों के अनुसार है।",
    input_mode: "इनपुट मोड",
    mode_amount: "एकमुश्त राशि",
    mode_installments: "किस्त अनुसूची",
    state_rules: "राज्य प्राधिकरण / नियम",
    amount_paid: "भुगतान की गई राशि (₹)",
    promised_date: "वचनबद्ध तिथि (कब्जे की)",
    actual_date: "वास्तविक / अंतिम तिथि",
    rera_spread: "राज्य कॉन्फ़िगरेशन से रेरा स्प्रेड (%)",
    latest_mclr: "नवीनतम एसबीआई उच्चतम एमसीएलआर (%)",
    override_mclr: "एक निश्चित एमसीएलआर के साथ ओवरराइड करें (अवधि-वार गतिशील दरों को अक्षम करें)",
    fixed_rate: "निश्चित प्रभावी दर:",
    dynamic_rate: "गतिशील एमसीएलआर + दिनांकित",
    spread_label: "स्प्रेड",
    btn_calculate: "अभी गणना करें",
    btn_calculating: "गणना हो रही है...",
    
    // Report
    report_title: "रेरा ब्याज गणना रिपोर्ट",
    report_subtitle: "रेरा हब पेनल्टी कैलकुलेटर द्वारा जनरेट किया गया",
    btn_share: "साझा करें",
    btn_print: "रिपोर्ट प्रिंट करें",
    stat_principal: "मूलधन राशि",
    stat_interest: "अर्जित ब्याज",
    stat_total: "कुल भुगतान",
    stat_delay: "देरी की अवधि",
    stat_days: "दिन",
    
    // Financial Analytics
    analytics_title: "वित्तीय विश्लेषण",
    principal_share: "मूलधन का हिस्सा",
    interest_share: "ब्याज का हिस्सा",
    daily_rate: "दैनिक दर",
    monthly_accrual: "मासिक संचय",
    avg_daily_interest: "औसत दैनिक ब्याज",
    disclaimer: "यह रिपोर्ट केवल सूचनात्मक उद्देश्यों के लिए है। आधिकारिक रेरा फाइलिंग के लिए किसी कानूनी पेशेवर से परामर्श लें।",
    methodology_title: "कार्यप्रणाली नोट:",
    methodology_dynamic: "डिफ़ॉल्ट रूप से यह कैलकुलेटर देरी के प्रत्येक खंड के लिए एसबीआई उच्चतम एमसीएलआर और दिनांकित राज्य स्प्रेड कॉन्फ़िगरेशन लागू करता है। संदर्भ के लिए भारित-औसत दर दिखाई गई है।",
    methodology_fixed: "पूरी देरी की अवधि में एक निश्चित एमसीएलआर ओवरराइड का उपयोग किया गया था।",
    methodology_spreads: "राज्य स्प्रेड क्यूरेटेड फाइलों से आते हैं",
    methodology_mclr: "एमसीएलआर स्रोत",
    
    // Form M Workspace
    workspace_eyebrow: "इंटरएक्टिव लीगल असिस्टेंट",
    workspace_title: "रेरा शिकायत तैयार करें (फॉर्म एम)",
    workspace_lead: "नीचे अपनी आधिकारिक राज्य शिकायत याचिका को प्री-फिल करें, विवरण संपादित करें और सीधे निर्यात करें।",
    section_edit_details: "1. याचिका विवरण संपादित करें",
    label_cname: "शिकायतकर्ता का नाम",
    label_caddress: "शिकायतकर्ता का पता",
    label_ccontact: "शिकायतकर्ता संपर्क (ईमेल / फोन)",
    label_pname: "परियोजना का नाम",
    label_promoter: "प्रमोटर / डेवलपर का नाम",
    label_promoter_addr: "प्रमोटर का पता",
    label_reg_no: "रेरा पंजीकरण संख्या",
    label_booking_date: "बुकिंग की तारीख",
    label_agreement_date: "बिक्री के लिए समझौते की तारीख",
    
    section_workspace: "2. शिकायत ड्राफ्ट कार्यक्षेत्र",
    placeholder_editor: "ड्राफ्ट सामग्री यहां दिखाई देगी...",
    btn_download_word: "वर्ड डाउनलोड करें (.doc)",
    btn_download_pdf: "पीडीएफ डाउनलोड करें (.pdf)",
    btn_copy: "क्लिपबोर्ड पर कॉपी करें",
    btn_copied: "कॉपी हो गया",
    
    // FAQ Section
    faq_eyebrow: "रेरा कानूनी प्रश्नोत्तर",
    faq_title: "केंद्रीय और राज्य रेरा प्रश्नों के विशेषज्ञ उत्तर",
    faq_subtitle: "विषय · केवल जानकारी के लिए, कानूनी सलाह नहीं",
    
    // How-to Section
    howto_title: "अपने रेरा विलंबित कब्जे के ब्याज की गणना कैसे करें",
    howto_step1: "अपना राज्य चुनें — प्रत्येक प्राधिकरण अपना खुद का ब्याज सूत्र निर्धारित करता है (साधारण बनाम मासिक चक्रवृद्धि, और एमसीएलआर स्प्रेड)।",
    howto_step2: "महत्वपूर्ण तिथियां दर्ज करें — वचनबद्ध कब्जा और वास्तविक/अंतिम तिथि देरी की अवधि को परिभाषित करती हैं।",
    howto_step3: "भुगतान की गई राशि दर्ज करें — वह मूलधन जिस पर कब्जे में देरी की अवधि के लिए धारा 18 के तहत ब्याज का अनुमान लगाया जाता है।",
    howto_step4: "रिपोर्ट की समीक्षा करें — मूलधन, ब्याज, देरी के दिन और आपकी शिकायत फ़ाइल के लिए एक प्रिंट करने योग्य विवरण।",
    
    footer_desc: "रियल एस्टेट (विनियमन और विकास) अधिनियम, 2016 के तहत घर खरीदारों के लिए एक इंटरैक्टिव वैधानिक ब्याज अनुमानक।",
    footer_disclaimer: "अस्वीकरण: केवल अनुमान, धारा 18/19-शैली एसबीआई एमसीएलआर + स्प्रेड नियमों पर आधारित। वास्तविक फैसले मामले के तथ्यों की समीक्षा करने के बाद राज्य रेरा प्राधिकरण / न्यायनिर्णायक अधिकारी द्वारा लिए जाते हैं। कानूनी सलाह नहीं।"
  },
  mr: {
    hero_eyebrow: "कलम १८ वैधानिक व्याजाच्या अनुरूप",
    hero_title: "भरपाई कॅल्क्युलेटर",
    hero_lead: "तुमच्या महारेरा नुकसानभरपाईचा त्वरित अंदाज लावा — कलम १८ अंतर्गत वैधानिक व्याज, परतावा रक्कम आणि टप्प्याटप्प्याने देयक दिरंगाई व्याज.",
    btn_start: "कॅल्क्युलेटर सुरू करा",
    btn_change_state: "राज्य बदला",
    btn_faq: "कायदेशीर प्रश्नोत्तरे वाचा",
    
    // Calculator Form
    form_title: "तुमच्या रेरा भरपाईची गणना करा",
    form_lead: "कलम १८ अंतर्गत उशिरा ताबा मिळण्याबद्दल मिळणाऱ्या व्याजाचा अंदाज लावा, जो राज्य-विशिष्ट एसबीआय एमसीएलआर मार्गदर्शक तत्त्वांच्या आधारे आहे.",
    input_mode: "इनपुट मोड",
    mode_amount: "एकरकमी रक्कम",
    mode_installments: "हप्ता वेळापत्रक",
    state_rules: "राज्य प्राधिकरण / नियम",
    amount_paid: "भरलेली रक्कम (₹)",
    promised_date: "ताबा मिळण्याची वचनबद्ध तारीख",
    actual_date: "वास्तविक / अंतिम तारीख",
    rera_spread: "राज्य कॉन्फिगरेशनवरून रेरा स्प्रेड (%)",
    latest_mclr: "नवीनतम एसबीआय सर्वोच्च एमसीएलआर (%)",
    override_mclr: "ठराविक एमसीएलआरसह ओव्हरराइड करा (कालावधीनुसार बदलणारे दर बंद करा)",
    fixed_rate: "निश्चित प्रभावी दर:",
    dynamic_rate: "गतिशील एमसीएलआर + दिनांकित",
    spread_label: "स्प्रेड",
    btn_calculate: "आता गणना करा",
    btn_calculating: "गणना सुरू आहे...",
    
    // Report
    report_title: "रेरा व्याज गणना अहवाल",
    report_subtitle: "रेरा हब पेनल्टी कॅल्क्युलेटरद्वारे व्युत्पन्न",
    btn_share: "शेअर करा",
    btn_print: "अहवाल प्रिंट करा",
    stat_principal: "मुद्दल रक्कम",
    stat_interest: "अर्जित व्याज",
    stat_total: "एकूण मोबदला",
    stat_delay: "दिरंगाईचा कालावधी",
    stat_days: "दिवस",
    
    // Financial Analytics
    analytics_title: "वित्तीय विश्लेषण",
    principal_share: "मुद्दल वाटा",
    interest_share: "व्याज वाटा",
    daily_rate: "दैनिक दर",
    monthly_accrual: "मासिक संचय",
    avg_daily_interest: "सरासरी दैनिक व्याज",
    disclaimer: "हा अहवाल केवळ माहितीसाठी आहे. अधिकृत महारेरा तक्रार दाखल करण्यासाठी कायदेशीर सल्लागाराचा सल्ला घ्या.",
    methodology_title: "कार्यपद्धती टीप:",
    methodology_dynamic: "डीफॉल्टनुसार हे कॅल्क्युलेटर दिरंगाईच्या प्रत्येक टप्प्यासाठी एसबीआय सर्वोच्च एमसीएलआर आणि दिनांकित राज्य स्प्रेड कॉन्फिगरेशन लागू करते. संदर्भासाठी भारित सरासरी दर दर्शविला आहे.",
    methodology_fixed: "पूर्ण दिरंगाई कालावधीसाठी निश्चित एमसीएलआर ओव्हरराइड वापरला गेला.",
    methodology_spreads: "राज्य स्प्रेड क्युरेट केलेल्या फायलींमधून येतात",
    methodology_mclr: "एमसीएलआर स्त्रोत",
    
    // Form M Workspace
    workspace_eyebrow: "इंटरएक्टिव्ह लीगल असिस्टंट",
    workspace_title: "रेरा तक्रार अर्ज तयार करा",
    workspace_lead: "खाली तुमच्या अधिकृत राज्य तक्रार अर्जाचे तपशील भरा, संपादित करा आणि थेट डाऊनलोड करा.",
    section_edit_details: "1. अर्जाचे तपशील संपादित करा",
    label_cname: "तक्रारदाराचे नाव",
    label_caddress: "तक्रारदाराचा पत्ता",
    label_ccontact: "तक्रारदार संपर्क (ईमेल / फोन)",
    label_pname: "प्रकल्पाचे नाव",
    label_promoter: "प्रमोटर / डेव्हलपरचे नाव",
    label_promoter_addr: "प्रमोटरचा पत्ता",
    label_reg_no: "रेरा नोंदणी क्रमांक",
    label_booking_date: "बुकिंगची तारीख",
    label_agreement_date: "विक्री कराराची तारीख",
    
    section_workspace: "2. तक्रार मसुदा कार्यक्षेत्र",
    placeholder_editor: "मसुदा येथे दिसेल...",
    btn_download_word: "वर्ड डाउनलोड करा (.doc)",
    btn_download_pdf: "पीडीएफ डाउनलोड करा (.pdf)",
    btn_copy: "क्लिपबोर्डवर कॉपी करा",
    btn_copied: "कॉपी केले",
    
    // FAQ Section
    faq_eyebrow: "रेरा कायदेशीर प्रश्नोत्तरे",
    faq_title: "केंद्रीय आणि राज्य रेरा प्रश्नांची तज्ञ उत्तरे",
    faq_subtitle: "विषय · केवळ माहितीसाठी, कायदेशीर सल्ला नाही",
    
    // How-to Section
    howto_title: "तुमच्या रेरा उशिरा ताबा व्याजाची गणना कशी करावी",
    howto_step1: "तुमचे राज्य निवडा — प्रत्येक प्राधिकरण स्वतःचे व्याज सूत्र ठरवते (साधे विरुद्ध मासिक चक्रवाढ व्याज, आणि एमसीएलआर स्प्रेड).",
    howto_step2: "महत्वाच्या तारखा प्रविष्ट करा — वचनबद्ध ताबा तारीख आणि वास्तविक/अंतिम तारीख उशीर कालावधी ठरवतात.",
    howto_step3: "भरलेली रक्कम प्रविष्ट करा — मुद्दल रक्कम ज्यावर ताबा उशीर कालावधीसाठी कलम १८ अंतर्गत व्याजाचा अंदाज लावला जातो.",
    howto_step4: "अहवालाचे पुनरावलोकन करा — मुद्दल, व्याज, विलंबाचे दिवस आणि तुमच्या तक्रार फाईलसाठी प्रिंट करण्यायोग्य अहवाल.",
    
    footer_desc: "रिअल इस्टेट (नियमन आणि विकास) कायदा, २०१६ अंतर्गत घर खरेदीदारांसाठी एक संवादी वैधानिक व्याज अंदाजक.",
    footer_disclaimer: "अस्वीकरण: केवळ अंदाज, कलम १८/१९-शैली एसबीआय एमसीएलआर + स्प्रेड नियमांवर आधारित. प्रत्यक्ष निर्णय प्रकरणाच्या तथ्यांचे पुनरावलोकन केल्यानंतर राज्य रेरा प्राधिकरण / न्यायनिर्णय अधिकारी घेतात. कायदेशीर सल्ला नाही."
  },
  kn: {
    hero_eyebrow: "ಸೆಕ್ಷನ್ 18 ಶಾಸನಬದ್ಧ ಬಡ್ಡಿಗೆ ಅನುಗುಣವಾಗಿದೆ",
    hero_title: "ಪರಿಹಾರ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    hero_lead: "ನಿಮ್ಮ ರೇರಾ ಪರಿಹಾರವನ್ನು ತಕ್ಷಣವೇ ಅಂದಾಜು ಮಾಡಿ — ಸೆಕ್ಷನ್ 18 ರ ಅಡಿಯಲ್ಲಿ ಶಾಸನಬದ್ಧ ಬಡ್ಡಿ, ಮರುಪಾವತಿ ಮೊತ್ತಗಳು ಮತ್ತು ವಿಳಂಬ ಪಾವತಿಗಳ ಬಡ್ಡಿ.",
    btn_start: "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಪ್ರಾರಂಭಿಸಿ",
    btn_change_state: "ರಾಜ್ಯ ಬದಲಾಯಿಸಿ",
    btn_faq: "ಕಾನೂನು FAQ ವೀಕ್ಷಿಸಿ",
    
    // Calculator Form
    form_title: "ನಿಮ್ಮ ರೇರಾ ಪರಿಹಾರವನ್ನು ಲೆಕ್ಕಹಾಕಿ",
    form_lead: "ಸೆಕ್ಷನ್ 18 ರ ಅಡಿಯಲ್ಲಿ ವಿಳಂಬಿತ ಸ್ವಾಧೀನಕ್ಕಾಗಿ ಸ್ವೀಕರಿಸಬೇಕಾದ ಬಡ್ಡಿಯನ್ನು ಅಂದಾಜು ಮಾಡಿ, ಇದನ್ನು ರಾಜ್ಯ-ನಿರ್ದಿಷ್ಟ ಎಸ್‌ಬಿಐ ಎಂಸಿಎಲ್‌ಆರ್ ಮಾರ್ಗಸೂಚಿಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.",
    input_mode: "ಇನ್‌ಪುಟ್ ಮೋಡ್",
    mode_amount: "ಒಟ್ಟು ಮೊತ್ತ",
    mode_installments: "ಕಂತುಗಳ ವೇಳಾಪಟ್ಟಿ",
    state_rules: "ರಾಜ್ಯ ಪ್ರಾಧಿಕಾರ / ನಿಯಮಗಳು",
    amount_paid: "ಪಾವತಿಸಿದ ಮೊತ್ತ (₹)",
    promised_date: "ಭರವಸೆ ನೀಡಿದ ಸ್ವಾಧೀನ ದಿನಾಂಕ",
    actual_date: "ವಾಸ್ತವಿಕ / ಕೊನೆಯ ದಿನಾಂಕ",
    rera_spread: "ರಾಜ್ಯ ಕಾನ್ಫಿಗರೇಶನ್‌ನಿಂದ ರೇರಾ ಸ್ಪ್ರೆಡ್ (%)",
    latest_mclr: "ಇತ್ತೀಚಿನ ಎಸ್‌ಬಿಐ ಗರಿಷ್ಠ ಎಂಸಿಎಲ್‌ಆರ್ (%)",
    override_mclr: "ಸ್ಥಿರ ಎಂಸಿಎಲ್‌ಆರ್‌ನೊಂದಿಗೆ ಅತಿಕ್ರಮಿಸಿ (ಅವಧಿವಾರು ಕ್ರಿಯಾತ್ಮಕ ದರಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ)",
    fixed_rate: "ಸ್ಥಿರ ಪರಿಣಾಮಕಾರಿ ದರ:",
    dynamic_rate: "ಡೈನಾಮಿಕ್ ಎಂಸಿಎಲ್‌ಆರ್ + ದಿನಾಂಕಿತ",
    spread_label: "ಸ್ಪ್ರೆಡ್",
    btn_calculate: "ಈಗ ಲೆಕ್ಕಹಾಕಿ",
    btn_calculating: "ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...",
    
    // Report
    report_title: "ರೇರಾ ಬಡ್ಡಿ ಲೆಕ್ಕಾಚಾರದ ವರದಿ",
    report_subtitle: "ರೇರಾ ಹಬ್ ಪೆನಾಲ್ಟಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್‌ನಿಂದ ರಚಿಸಲಾಗಿದೆ",
    btn_share: "ಹಂಚಿಕೊಳ್ಳಿ",
    btn_print: "ವರದಿ ಪ್ರಿಂಟ್ ಮಾಡಿ",
    stat_principal: "ಅಸಲು ಮೊತ್ತ",
    stat_interest: "ಸಂಚಿತ ಬಡ್ಡಿ",
    stat_total: "ಒಟ್ಟು ಪಾವತಿ",
    stat_delay: "ವಿಳಂಬ ಅವಧಿ",
    stat_days: "ದಿನಗಳು",
    
    // Financial Analytics
    analytics_title: "ಹಣಕಾಸು ವಿಶ್ಲೇಷಣೆ",
    principal_share: "ಅಸಲು ಪಾಲು",
    interest_share: "ಬಡ್ಡಿ ಪಾಲು",
    daily_rate: "ದೈನಂದಿನ ದರ",
    monthly_accrual: "ಮಾಸಿಕ ಸಂಚಯ",
    avg_daily_interest: "ಸರಾಸರಿ ದೈನಂದಿನ ಬಡ್ಡಿ",
    disclaimer: "ಈ ವರದಿಯು ಕೇವಲ ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ. ಅಧಿಕೃತ ರೇರಾ ಸಲ್ಲಿಕೆಗಳಿಗಾಗಿ ಕಾನೂನು ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    methodology_title: "ವಿಧಾನದ ಟಿಪ್ಪಣಿ:",
    methodology_dynamic: "ಡೀಫಾಲ್ಟ್ ಆಗಿ ಈ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ವಿಳಂಬದ ಪ್ರತಿ ವಿಭಾಗಕ್ಕೆ ಎಸ್‌ಬಿಐ ಗರಿಷ್ಠ ಎಂಸಿಎಲ್‌ಆರ್ ಮತ್ತು ದಿನಾಂಕದ ರಾಜ್ಯ ಸ್ಪ್ರೆಡ್ ಕಾನ್ಫಿಗರೇಶನ್ ಅನ್ನು ಅನ್ವಯಿಸುತ್ತದೆ. ಉಲ್ಲೇಖಕ್ಕಾಗಿ ಸರಾಸರಿ ದರವನ್ನು ತೋರಿಸಲಾಗಿದೆ.",
    methodology_fixed: "ಪೂರ್ಣ ವಿಳಂಬ ಅವಧಿಗೆ ಸ್ಥಿರ ಎಂಸಿಎಲ್‌ಆರ್ ಅನ್ನು ಬಳಸಲಾಗಿದೆ.",
    methodology_spreads: "ರಾಜ್ಯ ಸ್ಪ್ರೆಡ್‌ಗಳು ಕ್ಯುರೇಟೆಡ್ ಫೈಲ್‌ಗಳಿಂದ ಬರುತ್ತವೆ",
    methodology_mclr: "ಎಂಸಿಎಲ್‌ಆರ್ ಮೂಲ",
    
    // Form M Workspace
    workspace_eyebrow: "ಸಂವಾದಾತ್ಮಕ ಕಾನೂನು ಸಹಾಯಕ",
    workspace_title: "ರೇರಾ ದೂರು ಅರ್ಜಿ ಸಿದ್ಧಪಡಿಸಿ (ಫಾರ್ಮ್ ಎಂ)",
    workspace_lead: "ಕೆಳಗೆ ನಿಮ್ಮ ಅಧಿಕೃತ ರಾಜ್ಯ ದೂರು ಅರ್ಜಿಯನ್ನು ಭರ್ತಿ ಮಾಡಿ, ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ ಮತ್ತು ನೇರವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
    section_edit_details: "1. ಅರ್ಜಿ ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
    label_cname: "ದೂರುದಾರರ ಹೆಸರು",
    label_caddress: "ದೂರುದಾರರ ವಿಳಾಸ",
    label_ccontact: "ದೂರುದಾರರ ಸಂಪರ್ಕ (ಇಮೇಲ್ / ಫೋನ್)",
    label_pname: "ಯೋಜನೆಯ ಹೆಸರು",
    label_promoter: "ಪ್ರವರ್ತಕರು / ಡೆವಲಪರ್ ಹೆಸರು",
    label_promoter_addr: "ಪ್ರವರ್ತಕರ ವಿಳಾಸ",
    label_reg_no: "ರೇರಾ ನೋಂದಣಿ ಸಂಖ್ಯೆ",
    label_booking_date: "ಬುಕಿಂಗ್ ದಿನಾಂಕ",
    label_agreement_date: "ಮಾರಾಟ ಒಪ್ಪಂದದ ದಿನಾಂಕ",
    
    section_workspace: "2. ದೂರು ಕರಡು ಕಾರ್ಯಕ್ಷೇತ್ರ",
    placeholder_editor: "ಕರಡು ಇಲ್ಲೇ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ...",
    btn_download_word: "ವರ್ಡ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (.doc)",
    btn_download_pdf: "ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (.pdf)",
    btn_copy: "ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಿ",
    btn_copied: "ನಕಲಿಸಲಾಗಿದೆ",
    
    // FAQ Section
    faq_eyebrow: "ರೇರಾ ಕಾನೂನು FAQ",
    faq_title: "ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ರೇರಾ ಪ್ರಶ್ನೆಗಳಿಗೆ ತಜ್ಞರ ಉತ್ತರಗಳು",
    faq_subtitle: "ವಿಷಯಗಳು · ಕೇವಲ ಮಾಹಿತಿಗಾಗಿ, ಕಾನೂನು ಸಲಹೆಯಲ್ಲ",
    
    // How-to Section
    howto_title: "ನಿಮ್ಮ ರೇರಾ ವಿಳಂಬಿತ ಸ್ವಾಧೀನದ ಬಡ್ಡಿಯನ್ನು ಲೆಕ್ಕಹಾಕುವುದು ಹೇಗೆ",
    howto_step1: "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ — ಪ್ರತಿ ಪ್ರಾಧಿಕಾರವು ತನ್ನದೇ ಆದ ಬಡ್ಡಿ ಸೂತ್ರವನ್ನು ನಿಗದಿಪಡಿಸುತ್ತದೆ (ಸರಳ ಮತ್ತು ಮಾಸಿಕ ಚಕ್ರಬಡ್ಡಿ, ಮತ್ತು ಎಂಸಿಎಲ್‌ಆರ್ ಸ್ಪ್ರೆಡ್).",
    howto_step2: "ಪ್ರಮುಖ ದಿನಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ — ಭರವಸೆ ನೀಡಿದ ಸ್ವಾಧೀನ ಮತ್ತು ವಾಸ್ತವಿಕ/ಕೊನೆಯ ದಿನಾಂಕ ವಿಳಂಬ ಅವಧಿಯನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ.",
    howto_step3: "ಪಾವತಿಸಿದ ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ — ಸ್ವಾಧೀನ ವಿಳಂಬ ಅವಧಿಗೆ ಸೆಕ್ಷನ್ 18 ರ ಅಡಿಯಲ್ಲಿ ಬಡ್ಡಿಯನ್ನು ಅಂದಾಜು ಮಾಡುವ ಅಸಲು ಮೊತ್ತ.",
    howto_step4: "ವರದಿಯನ್ನು ಪರಿಶೀಲಿಸಿ — ನಿಮ್ಮ ದೂರು ಫೈಲ್‌ಗಾಗಿ ಅಸಲು, ಬಡ್ಡಿ, ವಿಳಂಬದ ದಿನಗಳು ಮತ್ತು ಮುದ್ರಿಸಬಹುದಾದ ವರದಿ.",
    
    footer_desc: "ರಿಯಲ್ ಎಸ್ಟೇಟ್ (ನಿಯಂತ್ರಣ ಮತ್ತು ಅಭಿವೃದ್ಧಿ) ಕಾಯ್ದೆ, 2016 ರ ಅಡಿಯಲ್ಲಿ ಮನೆ ಖರೀದಿದಾರರಿಗೆ ಒಂದು ಸಂವಾದಾತ್ಮಕ ಶಾಸನಬದ್ಧ ಬಡ್ಡಿ ಅಂದಾಜು ಸಾಧನ.",
    footer_disclaimer: "ಹಕ್ಕುತ್ಯಾಗ: ಅಂದಾಜುಗಳು ಮಾತ್ರ, ಸೆಕ್ಷನ್ 18/19 ರ ಎಸ್‌ಬಿಐ ಎಂಸಿಎಲ್‌ಆರ್ + ಸ್ಪ್ರೆಡ್ ನಿಯಮಗಳ ಆಧಾರದ ಮೇಲೆ. ನಿಜವಾದ ತೀರ್ಪುಗಳನ್ನು ರಾಜ್ಯ ರೇರಾ ಪ್ರಾಧಿಕಾರ / ನ್ಯಾಯಾಧಿಕಾರಿಗಳು ಪ್ರಕರಣದ ಸತ್ಯಾಂಶಗಳನ್ನು ಪರಿಶೀಲಿಸಿದ ನಂತರ ನಿರ್ಧರಿಸುತ್ತಾರೆ. ಕಾನೂನು ಸಲಹೆಯಲ್ಲ."
  }
};

export function translate(key, lang = "en") {
  const translations = UI_TRANSLATIONS[lang] || UI_TRANSLATIONS.en;
  return translations[key] || UI_TRANSLATIONS.en[key] || key;
}
